- name: start master kubernetes API service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
