- name: setting to a machine timezone
  timezone:
    name: "{{ timezone }}"
  when: enable_timezone is defined

- name: Off all of swap partitions/disk or file
  shell: swapoff -a
  when: disable_swap is defined

- name: kubernetes repos file
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

#- name: disable to SWAP partition or a file
#  replace:
#    path: /etc/fstab
#    regrex: '^(.+?\sswap\s+sw\s+.*)$'
#    replace: "#\1"
#  when: disable_swap is defined

- name: kubernetes configuration setup up for modules and POSIX
  copy:
    src: "files/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'k8s-ipvs.conf', dest: "/etc/modules-load.d/" }
    - { src: 'k8s-posix.conf', dest: "/etc/security/limits.d/" }

- name: sysctl configuration file copy to sysctl.d
  template:
    src: k8s-sysctl.conf.j2
    dest: /etc/sysctl.d/

- name: enable to systemd-module-load
  systemd:
    name: systemd-modules-load
    state: started
    enabled: yes

- name: prepare directories for install k8s
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes/pki/etcd
    - /etc/kubernetes/pki
    - /etc/kubernetes/manifests
    - /var/log/kubernetes
    - /var/lib/kubelet

- name: set to hostname
  hostname: 
    name: "{{ hostname }}"

- name: setup up to chronyd server
  template:
    src: chronyd.conf.j2
    dest: /etc/chronyd.conf

- name: systemctl start and enable to chronyd
  systemd:
    name: chronyd
    enabled: yes
